[workspace]
authors = [
    "Prince Ravi Leow <prince.ravi.leow@sund.ku.dk>",
    "Neil Scheidwasser <neil.clow@sund.ku.dk>",
    "David Duchêne <david.duchene@sund.ku.dk>",
]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]
name = "PlayClass"
version = "1.0.0"

[system-requirements]
cuda = "12"

[environments]
default = { solve-group = "default" }
tracker = { features = ["tracker"], solve-group = "tracker" }
gs2 = { features = ["gs2"], solve-group = "gs2" }

[tasks]
track-best = "python -m pipeline.run_tracker"
track-all = "bash pipeline/run_tracker_all.sh"
track-yolo = "bash pipeline/run_tracker_all.sh yolo"
track-sam3 = "bash pipeline/run_tracker_all.sh sam3"
track-gs2 = "bash pipeline/run_tracker_all.sh gs2"
eval-all = "bash pipeline/run_tracker_all.sh --eval"
eval-yolo = "bash pipeline/run_tracker_all.sh yolo --eval"
eval-sam3 = "bash pipeline/run_tracker_all.sh sam3 --eval"
eval-gs2 = "bash pipeline/run_tracker_all.sh gs2 --eval"
score-tracker = "python -m pipeline.eval_tracker_all score"
prepare-tracker = "python -m pipeline.eval_tracker_all prepare"
test-postprocessing = "python -m pytest tests/test_tracking_postprocessing.py -v"
test-labels = "python -m pytest tests/test_labels.py -v"
test-features = "python -m pytest tests/test_features.py -v"
test-post-build = "python -m pytest tests/test_post_build_dataset.py -v"

[dependencies]
python = ">=3.11,<3.12"
pytest = ">=9.0.2,<10"

[pypi-dependencies]
transformers = { git = "https://github.com/huggingface/transformers", rev = "v5.0.0rc2" }
accelerate = ">=1.12.0"
numpy = ">=1.2.6,<2"
loguru = ">=0.7.3"
matplotlib = ">=3.7.0,<4"
pandas = ">=3.0.0,<4"
pillow = ">=12.1.0,<13"
pycocotools = ">=2.0.11,<3"
opencv-python = ">=4.11.0.86, <5"
openpyxl = ">=3.1.0,<4"
supervision = ">=0.27.0,<0.28"
torchcodec = "==0.9"
torch = "==2.9.1+cu126"
torchvision = "==0.24.1+cu126"

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu126"]

[feature.gs2.pypi-dependencies]
setuptools = "*"

[feature.gs2.tasks]
setup_gs2 = "bash scripts/setup_gs2.sh"

[feature.tracker.pypi-dependencies]
omegaconf = ">=2.3.0"
simpler-timer = ">=0.0.2"
motmetrics = ">=1.4.0"

[feature.tracker.tasks]
test_tracker = "CUDA_VISIBLE_DEVICES=0 pixi run -e tracker python -m pytest tests/test_tracker.py -v"
